export const Permissoes = {
  // Usuários
  READ_USUARIOS: 'READ_USUARIOS',
  READ_USUARIO_BY_ID: 'READ_USUARIO_BY_ID',
  CREATE_USUARIO: 'CREATE_USUARIO',
  UPDATE_USUARIO: 'UPDATE_USUARIO',
  DELETE_USUARIO: 'DELETE_USUARIO',
  RESTORE_USUARIO: 'RESTORE_USUARIO',
  READ_USUARIO_EMPRESAS: 'READ_USUARIO_EMPRESAS',

  // Empresas
  READ_EMPRESAS: 'READ_EMPRESAS',
  READ_EMPRESA_BY_ID: 'READ_EMPRESA_BY_ID',
  CREATE_EMPRESA: 'CREATE_EMPRESA',
  UPDATE_EMPRESA: 'UPDATE_EMPRESA',
  DELETE_EMPRESA: 'DELETE_EMPRESA',
  ADD_USER_TO_EMPRESA: 'ADD_USER_TO_EMPRESA',
  READ_EMPRESA_USERS: 'READ_EMPRESA_USERS',

  // Perfis
  READ_PERFIS: 'READ_PERFIS',
  READ_PERFIL_BY_ID: 'READ_PERFIL_BY_ID',
  CREATE_PERFIL: 'CREATE_PERFIL',
  UPDATE_PERFIL: 'UPDATE_PERFIL',
  DELETE_PERFIL: 'DELETE_PERFIL',

  // Permissões
  READ_PERMISSOES: 'READ_PERMISSOES',
  READ_PERMISSAO_BY_ID: 'READ_PERMISSAO_BY_ID',
};

export const Roles = {
  ADMIN: 'ADMIN',
  USER: 'USER',
};
